# Site settings
title: Mathieu Breier — Data Science & Economics
description: Portfolio of Mathieu Breier, Data Science and Economics of Energy MSc student at BSE. Spatial analysis, event studies, econometrics and more.
baseurl: "" # no subpath — served at root
url: "https://mathieubreier.github.io"

# User settings
username: Mathieu Breier
user_description: Welcome to my website where I share some of my projects. I am currently a Master student in Data Science at the Barcelona School of Economics (BSE). You can explore the projects I have included below.
user_title: Data Science and Economics of Energy
email: breiermathieu@gmail.com
#twitter_username: lorem_ipsum
github_username:  mtbrr26
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "G-M6V4BZTRRN"

exclude: ['package.json', 'src' , 'node_modules']
